@startuml

title Forgon del Barrio.

class Cliente{
-Nombre
-Apellido

}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class RestauranteForgon{
-Nombre
-HistorialPedidos: Pedido[]

+GuardarHistorialPedido()

}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class Pedido{
#IdPedido
-FechaPedido: Date
-ProductosFinales: Item[]

+CalcularPrecioTotalPedidoSinDescuentos()
+AgregarItems()
+QuitarItems()
+GetFechaPedido()

}



class PedidoSalon{
-NumerodeMesa: number
}



class PedidoRetirar{
-HorarioDeRetiro: string

}



class PedidoEnvio{
-DomicilioPedido : string
-CostodeEnvio : number
}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

' CADETE QUE ES? TIENE OBRA SOCIAL?


'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class Estacion{

-NombreEstacion

+RecibirPedido(Pedido:Pedidos)
+EstadoPedido()

}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

'PADRE DE ARTICULO Y COMBO
abstract class Item{
#Nombre: String
#ID: number
'A CHECKEAR
'constructor(Nombre:String,ID:number){'
'this.Nombre = Nombre
'this.ID = ID}

+abstract PrecioFinal():number
}



enum Categoria{
ENTRADA,
PLATOPRINCIPAL,
BEBIDA,
POSTRE,
}



class Articulo{
-PrecioArticulo : Number
-Categoria : Categoria
'A CHECKEAR
'constructor(PrecioArticulo:PrecioArticulo, Categoria: Categoria){
'    super(Nombre,ID);
'    this.PrecioArticulo = PrecioArticulo
'    this.Categoria = Categoria}

+PrecioFinal()
'return this.PrecioArticulo
}

'const Hamburguesita = new Articulo("Hamburguesa",12,9000,Categoria.PLATOPRINCIPAL);
'Hamburguesita.PrecioFinal(); (Retorna 9k)
'const Coquita = new Articulo ("Coquita",13,5000,Categoria.BEBIDA);


class Combo{
-PrecioCombo : PrecioCombo
-Articulos :Articulo[]
'constructor(){
'super('Parametros);
'this.PrecioCombo=PrecioCombo
'this.Articulos: [];
'}

+AgregarArticulo()
'this.Articulos.push(articulo);
+PrecioFinal()
'No tan claro como funciona este metodo en Combos
}



'const COMBO1 =new Combo("Combo 1",1,Descuentode30);
'COMBO1.AgregarArticulo(Hamburguesita);
'COMBO1.AgregarArticulo(Coquita);


abstract class PrecioCombo{
+abstract CalcularPrecio(Articulo: Articulo[]) 
'Calcular Precio va a calcular en las clases de abajo por separado el precio final del combo con distintos descuentos.
}


class DescuentoPorcentualCombo{
-PorcentajeDescuentoCombo: number
' +CalcularPrecio() Lo implementa o hereda (duda) desde PrecioCombo
}

'cont Descuentode30 = new DescuentoPorcentualCombo(30)
'Descuento30.CalcularPrecio()


class DescuentoFijoCombo{
-MontoDescontadoCombo: number
' +CalcularPrecio() Lo implementa o hereda (duda) desde PrecioCombo
}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum DiaSemana{
LUNES,
MARTES, 
MIERCOLES, 
JUEVES, 
VIERNES, 
SABADO, 
DOMINGO, 
}



enum TipoDeMetodoDePago{
EFECTIVO,
TARJETA,
BILLETERAVIRTUAL,
}



abstract class MetodoDePago{

#NombreMetodoDePago: String
#TipoDeMetodoDePago: TipoDeMetodoDePago

+GetMetodoDePago():string
+GetTipoDeMetodoDePago(): TipoDeMetodoDePago
}



class Efectivo{

}



class Tarjetas{

}



class BilleteraVirtual{

}



abstract class Descuento{

#PorcentajeDescuento:number

+EsAplicable():boolean 
+CantidadDeDescuento():number 
+GetPorcentajeDescuento():number
+AplicarDescuento():number

}


class DescuentoPorDia{

-Dia: DiaSemana

+EsAplicable():boolean

}

class DescuentoPorMetodoDePago{

-MetodoDePago:TipoDeMetodoDePago

+EsAplicable():boolean

}

class Caja{

-Pedidos: Pedido
-MetodoDePago: MetodoDePago

+CompetenciaDeDescuentos()
+CobrarPrecioFinalConDescuento()
+GetMetodoDePago()
+getDiaPedido()

}

'////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
' Relaciones

Pedido <|-- PedidoEnvio
Pedido <|-- PedidoRetirar
Pedido <|-- PedidoSalon
Pedido o-- Item

Item <|-- Articulo
Item <|-- Combo


MetodoDePago <|-- Efectivo
MetodoDePago <|-- Tarjetas
MetodoDePago <|-- BilleteraVirtual

Descuento <|-- DescuentoPorMetodoDePago
Descuento <|-- DescuentoPorDia

PrecioCombo <|-- DescuentoFijoCombo
PrecioCombo <|-- DescuentoPorcentualCombo

Combo o-- Articulo
Combo *-- PrecioCombo

Caja o-- MetodoDePago
Caja o-- Pedido
Caja o-- Descuento

Estacion -- Pedido

RestauranteForgon o-- Estacion
RestauranteForgon o-- Pedido
RestauranteForgon -- Cliente
RestauranteForgon *-- Caja

@enduml

