@startuml

title Forgon del Barrio.

class Cliente{
-Nombre
-Apellido

}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

class RestauranteForgon{
-Nombre
-HistorialPedidos: Pedido[]

+GuardarHistorialPedido()

}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum EstadoDePedido{
    -ENCONSTRUCCION
    -CONFIRMADO
    -FINALIZADO
}

abstract class Pedido{
#IdPedido
-FechaPedido: DiaSemana
-ProductosFinales: Item[]
-EstadoPedido:EstadoDePedido

+CalcularPrecioTotalPedidoSinDescuentos()
+AgregarItems()
+QuitarItems()
+GetFechaPedido()
+SetMontoFinalCobrado()
+GetMontoFinalCobrado()
+ConfirmarPedido()

}



class PedidoSalon{
-NumerodeMesa: number

}



class PedidoRetirar{
-HorarioDeRetiro: string

}



class PedidoEnvio{
-DomicilioPedido : string
-CostodeEnvio : number
}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

' CADETE QUE ES? TIENE OBRA SOCIAL?


'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
enum TipoDeEstacion{
    -
    -
    -
    -
}

class Estacion{

-NombreEstacion
-TipoDeEstacion: TipoDeEstacion

+RecibirPedido(Pedido:Pedidos)
+EstadoPedido()

}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

'PADRE DE ARTICULO Y COMBO
abstract class Item{
#Nombre: String
#ID: number
'A CHECKEAR
'constructor(Nombre:String,ID:number){'
'this.Nombre = Nombre
'this.ID = ID}

+abstract PrecioFinal():number
+
}



enum Categoria{
ENTRADA,
PLATOPRINCIPAL,
BEBIDA,
POSTRE,
}


'FALTARIA ESTADO DE ARTICULO PARA QUE LA ESTACION VAYA CAMBIANDOLO DESPUES
class Articulo{
-PrecioArticulo : Number
-Categoria : Categoria
-Estacion: TipoDeEstacion
'A CHECKEAR
'constructor(PrecioArticulo:PrecioArticulo, Categoria: Categoria){
'    super(Nombre,ID);
'    this.PrecioArticulo = PrecioArticulo
'    this.Categoria = Categoria}

+PrecioFinal()
+GetEstacion()
}

'const Hamburguesita = new Articulo("Hamburguesa",12,9000,Categoria.PLATOPRINCIPAL);
'Hamburguesita.PrecioFinal(); (Retorna 9k)
'const Coquita = new Articulo ("Coquita",13,5000,Categoria.BEBIDA);


class Combo{
-PrecioCombo : PrecioCombo
-Articulos :Articulo[]
'constructor(){
'super('Parametros);
'this.PrecioCombo=PrecioCombo
'this.Articulos: [];
'}

+AgregarArticulo()
'this.Articulos.push(articulo);
+PrecioFinal()
+GetArticulos()
}



'const COMBO1 =new Combo("Combo 1",1,Descuentode30);
'COMBO1.AgregarArticulo(Hamburguesita);
'COMBO1.AgregarArticulo(Coquita);


abstract class PrecioCombo{
+abstract CalcularPrecio(Articulo: Articulo[]) 
'Calcular Precio va a calcular en las clases de abajo por separado el precio final del combo con distintos descuentos.
}


class DescuentoPorcentualCombo{
-PorcentajeDescuentoCombo: number
' +CalcularPrecio() Lo implementa o hereda (duda) desde PrecioCombo
}

'cont Descuentode30 = new DescuentoPorcentualCombo(30)
'Descuento30.CalcularPrecio()


class DescuentoFijoCombo{
-MontoDescontadoCombo: number
' +CalcularPrecio() Lo implementa o hereda (duda) desde PrecioCombo
}

'//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////

enum DiaSemana{
LUNES,
MARTES, 
MIERCOLES, 
JUEVES, 
VIERNES, 
SABADO, 
DOMINGO, 
}



enum TipoDeMetodoDePago{
EFECTIVO,
TARJETA,
BILLETERAVIRTUAL,
}



abstract class MetodoDePago{

#NombreMetodoDePago: String
#TipoDeMetodoDePago: TipoDeMetodoDePago

}



class Efectivo{

}



class Tarjetas{

}



class BilleteraVirtual{

}



abstract class Descuento{
#PorcentajeDescuento:number
+EsAplicable(Caja:Caja):boolean 
+CantidadDeDescuento(Cantidad:number):number 
}


class DescuentoPorDia{
-Dia: DiaSemana
+EsAplicable(Caja:Caja):boolean
 'return if(this.Caja.Pedido.GetFechaPedido()=== this.Dia);
'const DescuentoLunes = New DiaDescuentos(DiaSemana.LUNES,20)
}

class DescuentoPorMetodoDePago{
-MetodoDePago:TipoDeMetodoDePago

+EsAplicable(Caja:Caja):boolean
'return if(this.Caja.GetMetodoDePago === This.MetodoDePago.TipoDeMetodoDePago)
}

class Caja{
-Pedidos: Pedido
-MetodoDePago: MetodoDePago

+CompetenciaDeDescuentos(efectivo: Descuento, dia:Descuento)
'Va a devolver la competencia entre descuentos creados en las instancias del diadescuento o metododepago establecido con descuento
'Seguramente se invocando el metodo EsAplicable verificando si es true o false y comparando cual es mas grande
+CobrarPrecioFinalConDescuento()
'Va a recibir el monto total del pedido y va a aplicar desde el metodo competencia cual es el porcentaje mas alto y va a descontarselo al total
+GetMetodoDePago()
+getDiaPedido()
}

'////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////////
' Relaciones

Pedido <|-- PedidoEnvio
Pedido <|-- PedidoRetirar
Pedido <|-- PedidoSalon
Pedido o-- Item

Item <|-- Articulo
Item <|-- Combo


MetodoDePago <|-- Efectivo
MetodoDePago <|-- Tarjetas
MetodoDePago <|-- BilleteraVirtual

Descuento <|-- DescuentoPorMetodoDePago
Descuento <|-- DescuentoPorDia

PrecioCombo <|-- DescuentoFijoCombo
PrecioCombo <|-- DescuentoPorcentualCombo

Combo o-- Articulo
Combo *-- PrecioCombo

Caja o-- MetodoDePago
Caja o-- Pedido
Caja o-- Descuento

Estacion -- Pedido

RestauranteForgon o-- Estacion
RestauranteForgon o-- Pedido
RestauranteForgon -- Cliente
RestauranteForgon *-- Caja

@enduml